### PR TITLE
Add support for release and rollback to savepoint syntax

### PR DESCRIPTION
**Pull request by CDThomas**
This PR adds support for:
* `RELEASE SAVEPOINT savepoint_name` statements
* `TO SAVEPOINT savepoint_name` in `ROLLBACK` statements.

### CODE REVIEW

**Review by tobyhede — APPROVED** [review]
LGTM

**Comment by freshtonic** [comment]
If we're going to get this accepted upstream it's probably best not to change formatting.

Otherwise looks awesome!

**Comment by CDThomas** [comment]
> If we're going to get this accepted upstream it's probably best not to change formatting.
> 
> Otherwise looks awesome!

Thanks @freshtonic!

Yeah I'm a bit confused by the formatting changes, but `cargo fmt` insisted. I'm using the same Rust version and formatter settings as upstream CI, so I have no clue why the formatter decided that these changes only need to happen now. Spent a good 10 min trying to revert them.

**Comment by CDThomas** [comment]
> > If we're going to get this accepted upstream it's probably best not to change formatting.
> > Otherwise looks awesome!
> 
> Thanks @freshtonic!
> 
> Yeah I'm a bit confused by the formatting changes, but `cargo fmt` insisted. I'm using the same Rust version and formatter settings as upstream CI, so I have no clue why the formatter decided that these changes only need to happen now. Spent a good 10 min trying to revert them.

Scratch that. Looks like comments are part of rustfmt's heuristics for choosing when to split things into multiple lines. I was able to revert the formatting changes and appease rustfmt in ~~[this commit](https://github.com/cipherstash/sqlparser-rs/pull/4/commits/0126ab4fdfd25944d540261ccce5673deb9d5cc8)~~ (squashed) where I also added in some docs.

**Pull request merged**
